version: '3.1'

services:

  pg:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "myuser", "-d", "mydatabase"]
      interval: 5s
      timeout: 5s
      retries: 10

  minio:
    image: quay.io/minio/minio 
    container_name: minio1
    ports:
      - 9000:9000
      - 9090:9090
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: myuser
      MINIO_ROOT_PASSWORD: mypassword
    command: ["minio", "server", "--console-address", ":9090", "/data"]

volumes:
  pg_data:
  minio_data: